travis: fix dead CI build in case of 3.2_with_system_site_packages
This is caused by an update of the base distribution in CI environment
in July  2017:
https://docs.travis-ci.com/user/precise-to-trusty-migration-guide/

As the point of using native (with site-packages) python is the
significant boost in getting the prerequisites ready (especially with
lxml that takes time for on-demand build when installed from pip),
just bump the version to 3.4_with_system_site_packages[*].

But as we claim support for python 3.2+, keep 3.2 in the list, only
lacking the mentioned speedup, though still bearable (note that we need
to upper-limit the lxml version in that case as the newest ones on PyPI
as of this commit, 4.1.1 + 4.1.0, seems to be encumbered with Cython
version [0.27.3?] not compatible with that target python, causing
the build to fail on: src/lxml/etree.c:101:6: error:
#error Cython requires Python 2.6+ or Python 3.3+).
In the same go, also add "3.7-dev" to the test matrix for good measure.

[*] see also
https://github.com/travis-ci/travis-ci/issues/8336#issuecomment-327617263

Signed-off-by: Jan Pokorný <jpokorny@redhat.com>